name: Automatic build and deployment

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - feature/AM-46-docker-deploy
    paths:
      - docker/**
      - .github/workflows/deploy-infra.yml

# GLOBAL ENVIRONMENT VARIABLES
env:
  OCI_TENANCY_NS: axkiihq3lcps
  OCI_REGISTRY: eu-paris-1.ocir.io
  OCI_REPOSITORY: grenadille/website
  OCI_GITHUB_USERNAME: ${{ secrets.OCI_GITHUB_USERNAME }}
  OCI_GITHUB_PASSWORD: ${{ secrets.OCI_GITHUB_PASSWORD }}
  DOCKERFILE: docker/Dockerfile

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OCI_REGISTRY }}
          username: ${{ env.OCI_TENANCY_NS }}/${{ env.OCI_GITHUB_USERNAME }}
          password: ${{ env.OCI_GITHUB_PASSWORD }}

      - name: Set variables
        run: |
          echo "REPOSITORY=${{ env.OCI_REGISTRY }}/${{ env.OCI_TENANCY_NS }}/${{ env.OCI_REPOSITORY }}" >> $GITHUB_ENV

      - name: Build and push Docker image with latest tag
        run: |
          DOCKER_BUILDKIT=1 docker build -f ${{ env.DOCKERFILE }} -t ${{ env.REPOSITORY }}:latest .
          docker push ${{ env.REPOSITORY }}:latest

      - name: Add version tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ${{ env.REPOSITORY }}:latest ${{ env.REPOSITORY }}:${GITHUB_REF#refs/tags/}
          docker push ${{ env.REPOSITORY }}:${GITHUB_REF#refs/tags/}
