name: Automatic deployment

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

# GLOBAL ENVIRONMENT VARIABLES
env:
  OCI_TENANCY_NS: axkiihq3lcps
  OCI_BUCKET_NAME: website
  OCI_CLI_AUTH: api_key
  OCI_CLI_USER: ${{ secrets.OCI_GITHUB_OCID }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_GITHUB_PUBLIC_KEY_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_GITHUB_PRIVATE_KEY }}
  OCI_CLI_REGION: eu-paris-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:dist

      - name: Deploy files to OCI Object Storage
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: 'os object bulk-upload --namespace ${{ env.OCI_TENANCY_NS }} --bucket-name ${{ env.OCI_BUCKET_NAME }} --src-dir dist'
